block-list-secret-scan: []
branch: master
compact: true
directory:
  - .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
mask: []
quiet: true
secrets-history-timeout: 12h
secrets-scan-file-type: []
skip-check:
  - CKV_AWS_53
  - CKV_AWS_55
  - CKV_AWS_56
  - CKV2_AWS_6
summary-position: bottom
